import { useEffect, useRef, useState } from "react";

import {
  ArrowUp,
  Check,
  Copy,
  FileText,
  Image as ImageIcon,
  Paperclip,
  Plus,
  Sparkles,
  Upload,
  User,
  X,
} from "lucide-react";

import "./MultimodalChat.css";

const ACCEPTED_TYPES = [
  "image/png",
  "image/jpeg",
  "image/jpg",
  "image/webp",
  "application/pdf",
  "text/plain",
  "application/msword",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
];

const ACCEPTED_EXTENSIONS = ".png,.jpg,.jpeg,.webp,.pdf,.txt,.doc,.docx";

const SUGGESTIONS = [
  {
    icon: FileText,
    title: "Summarize",
    prompt:
      "Summarize the uploaded content and give me the most important points.",
  },
  {
    icon: Sparkles,
    title: "Explain",
    prompt: "Explain the uploaded content in simple language.",
  },
  {
    icon: ImageIcon,
    title: "Analyze image",
    prompt: "Analyze the uploaded image and explain what it contains.",
  },
  {
    icon: Check,
    title: "Key points",
    prompt: "Extract the most important information from the uploaded content.",
  },
];

function MultimodalChat() {
  const [messages, setMessages] = useState([]);
  const [input, setInput] = useState("");
  const [files, setFiles] = useState([]);
  const [isTyping, setIsTyping] = useState(false);
  const [copiedId, setCopiedId] = useState(null);

  const fileInputRef = useRef(null);
  const messagesEndRef = useRef(null);

  const hasConversation = messages.length > 0;

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({
      behavior: "smooth",
    });
  }, [messages, isTyping]);

  useEffect(() => {
    return () => {
      files.forEach((file) => {
        if (file.preview) {
          URL.revokeObjectURL(file.preview);
        }
      });
    };
  }, []);

  const formatFileSize = (bytes) => {
    if (bytes < 1024) {
      return `${bytes} B`;
    }

    if (bytes < 1024 * 1024) {
      return `${(bytes / 1024).toFixed(1)} KB`;
    }

    return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
  };

  const addFiles = (selectedFiles) => {
    const incomingFiles = Array.from(selectedFiles);

    const validFiles = incomingFiles.filter((file) =>
      ACCEPTED_TYPES.includes(file.type),
    );

    const invalidFiles = incomingFiles.filter(
      (file) => !ACCEPTED_TYPES.includes(file.type),
    );

    if (invalidFiles.length > 0) {
      alert(
        "Unsupported file detected. Please upload PDF, DOC, DOCX, TXT, JPG, JPEG, PNG or WEBP files.",
      );
    }

    const preparedFiles = validFiles.map((file) => ({
      id: `${file.name}-${file.lastModified}-${Math.random()}`,
      file,
      name: file.name,
      size: file.size,
      type: file.type,
      preview: file.type.startsWith("image/")
        ? URL.createObjectURL(file)
        : null,
    }));

    setFiles((previous) => [...previous, ...preparedFiles]);
  };

  const handleFileChange = (event) => {
    if (event.target.files?.length) {
      addFiles(event.target.files);
    }

    event.target.value = "";
  };

  const removeFile = (id) => {
    setFiles((previous) => {
      const target = previous.find((file) => file.id === id);

      if (target?.preview) {
        URL.revokeObjectURL(target.preview);
      }

      return previous.filter((file) => file.id !== id);
    });
  };

  const clearFiles = () => {
    files.forEach((file) => {
      if (file.preview) {
        URL.revokeObjectURL(file.preview);
      }
    });

    setFiles([]);
  };

  const getFileIcon = (file) => {
    if (file.type.startsWith("image/")) {
      return <ImageIcon size={19} />;
    }

    return <FileText size={19} />;
  };

  const getMockResponse = (question, uploadedFiles) => {
    if (uploadedFiles.length > 0) {
      const names = uploadedFiles.map((file) => file.name).join(", ");

      return `I've received your content.

Uploaded:
${names}

Your request:
${question || "Analyze the uploaded content."}

The multimodal AI interface is ready. Once we connect Jigyasa to Azure AI, the model will actually analyze the uploaded image, document, or text and generate a response based on its content.

The next backend stage will connect this interface to Spring Boot and Azure AI Foundry.`;
    }

    return `I received your question:

${question}

The chatbot interface is working. The next step is connecting Jigyasa to Azure AI so the response is generated by the actual AI model.`;
  };

  const sendMessage = (customPrompt = null) => {
    const messageText = (customPrompt !== null ? customPrompt : input).trim();

    if (!messageText && files.length === 0) {
      return;
    }

    const currentFiles = [...files];

    const userMessage = {
      id: Date.now(),
      role: "user",
      content:
        messageText ||
        `Analyze ${currentFiles.length} uploaded ${
          currentFiles.length === 1 ? "file" : "files"
        }.`,
      files: currentFiles,
    };

    setMessages((previous) => [...previous, userMessage]);

    setInput("");
    setFiles([]);
    setIsTyping(true);

    setTimeout(() => {
      const assistantMessage = {
        id: Date.now() + 1,
        role: "assistant",
        content: getMockResponse(messageText, currentFiles),
      };

      setMessages((previous) => [...previous, assistantMessage]);

      setIsTyping(false);
    }, 1200);
  };

  const handleKeyDown = (event) => {
    if (event.key === "Enter" && !event.shiftKey) {
      event.preventDefault();
      sendMessage();
    }
  };

  const handleDrop = (event) => {
    event.preventDefault();

    if (event.dataTransfer.files?.length) {
      addFiles(event.dataTransfer.files);
    }
  };

  const handleDragOver = (event) => {
    event.preventDefault();
  };

  const clearConversation = () => {
    clearFiles();
    setMessages([]);
    setInput("");
    setIsTyping(false);
  };

  const copyMessage = async (message) => {
    try {
      await navigator.clipboard.writeText(message.content);

      setCopiedId(message.id);

      setTimeout(() => {
        setCopiedId(null);
      }, 1500);
    } catch (error) {
      console.error("Unable to copy:", error);
    }
  };

  return (
    <div className="multimodal-page">
      <main className="multimodal-main">
        {!hasConversation ? (
          <section className="chat-welcome">
            <div className="chat-eyebrow">
              <span className="eyebrow-dot" />
              JIGYASA AI ASSISTANT
            </div>

            <h1>
              Your content.
              <br />
              <span>Your questions.</span>
            </h1>

            <p className="chat-description">
              Upload documents, images or text and let Jigyasa understand,
              analyze and explain them for you.
            </p>

            <div
              className="upload-zone"
              onDrop={handleDrop}
              onDragOver={handleDragOver}
              onClick={() => fileInputRef.current?.click()}
            >
              <div className="upload-icon">
                <Upload size={25} />
              </div>

              <h3>Upload your content</h3>

              <p>
                Drag & drop files here or <span>browse from your device</span>
              </p>

              <div className="supported-types">
                <span>PDF</span>
                <span>DOCX</span>
                <span>TXT</span>
                <span>JPG</span>
                <span>PNG</span>
              </div>
            </div>

            <input
              ref={fileInputRef}
              type="file"
              multiple
              accept={ACCEPTED_EXTENSIONS}
              onChange={handleFileChange}
              hidden
            />

            {files.length > 0 && (
              <FilePreviewList
                files={files}
                removeFile={removeFile}
                formatFileSize={formatFileSize}
                getFileIcon={getFileIcon}
              />
            )}

            <div className="or-divider">
              <span>OR</span>
            </div>

            <div className="welcome-composer">
              <textarea
                value={input}
                onChange={(event) => setInput(event.target.value)}
                onKeyDown={handleKeyDown}
                placeholder="Paste text or ask Jigyasa anything..."
                rows={3}
              />

              <div className="composer-actions">
                <button
                  type="button"
                  className="attach-button"
                  onClick={() => fileInputRef.current?.click()}
                  aria-label="Upload files"
                >
                  <Paperclip size={20} />
                </button>

                <button
                  type="button"
                  className="send-button"
                  disabled={!input.trim() && files.length === 0}
                  onClick={() => sendMessage()}
                  aria-label="Send message"
                >
                  <ArrowUp size={20} />
                </button>
              </div>
            </div>

            <div className="suggestion-grid">
              {SUGGESTIONS.map((suggestion) => {
                const Icon = suggestion.icon;

                return (
                  <button
                    key={suggestion.title}
                    type="button"
                    className="suggestion-card"
                    onClick={() => sendMessage(suggestion.prompt)}
                  >
                    <div className="suggestion-icon">
                      <Icon size={19} />
                    </div>

                    <span>{suggestion.title}</span>

                    <ArrowUp className="suggestion-arrow" size={17} />
                  </button>
                );
              })}
            </div>
          </section>
        ) : (
          <section className="chat-workspace">
            <header className="chat-header">
              <div className="chat-header-left">
                <div className="chat-ai-icon">
                  <Sparkles size={20} />
                </div>

                <div>
                  <h2>Jigyasa AI</h2>
                  <p>Multimodal learning assistant</p>
                </div>
              </div>

              <button
                type="button"
                className="new-chat-button"
                onClick={clearConversation}
              >
                <Plus size={18} />
                New chat
              </button>
            </header>

            <div className="messages-container">
              {messages.map((message) => (
                <div key={message.id} className={`message-row ${message.role}`}>
                  <div className="message-avatar">
                    {message.role === "assistant" ? (
                      <Sparkles size={17} />
                    ) : (
                      <User size={17} />
                    )}
                  </div>

                  <div className="message-content">
                    <div className="message-author">
                      {message.role === "assistant" ? "Jigyasa AI" : "You"}
                    </div>

                    {message.files?.length > 0 && (
                      <div className="message-files">
                        {message.files.map((file) => (
                          <div className="message-file" key={file.id}>
                            {file.preview ? (
                              <img src={file.preview} alt={file.name} />
                            ) : (
                              <div className="message-file-icon">
                                {getFileIcon(file)}
                              </div>
                            )}

                            <div>
                              <strong>{file.name}</strong>

                              <span>{formatFileSize(file.size)}</span>
                            </div>
                          </div>
                        ))}
                      </div>
                    )}

                    <div className="message-bubble">
                      {message.content.split("\n").map((line, index) => (
                        <p key={index}>{line || "\u00A0"}</p>
                      ))}
                    </div>

                    {message.role === "assistant" && (
                      <button
                        type="button"
                        className="copy-button"
                        onClick={() => copyMessage(message)}
                      >
                        {copiedId === message.id ? (
                          <>
                            <Check size={14} />
                            Copied
                          </>
                        ) : (
                          <>
                            <Copy size={14} />
                            Copy
                          </>
                        )}
                      </button>
                    )}
                  </div>
                </div>
              ))}

              {isTyping && (
                <div className="message-row assistant">
                  <div className="message-avatar">
                    <Sparkles size={17} />
                  </div>

                  <div className="message-content">
                    <div className="message-author">Jigyasa AI</div>

                    <div className="typing-bubble">
                      <span />
                      <span />
                      <span />
                    </div>
                  </div>
                </div>
              )}

              <div ref={messagesEndRef} />
            </div>

            <div className="chat-input-area">
              {files.length > 0 && (
                <FilePreviewList
                  files={files}
                  removeFile={removeFile}
                  formatFileSize={formatFileSize}
                  getFileIcon={getFileIcon}
                />
              )}

              <div className="chat-composer">
                <button
                  type="button"
                  className="composer-attach"
                  onClick={() => fileInputRef.current?.click()}
                  aria-label="Attach files"
                >
                  <Paperclip size={20} />
                </button>

                <textarea
                  value={input}
                  onChange={(event) => setInput(event.target.value)}
                  onKeyDown={handleKeyDown}
                  placeholder="Ask Jigyasa about your content..."
                  rows={1}
                />

                <button
                  type="button"
                  className="composer-send"
                  disabled={!input.trim() && files.length === 0}
                  onClick={() => sendMessage()}
                  aria-label="Send message"
                >
                  <ArrowUp size={19} />
                </button>
              </div>

              <p className="chat-disclaimer">
                Jigyasa AI may make mistakes. Verify important information.
              </p>
            </div>

            <input
              ref={fileInputRef}
              type="file"
              multiple
              accept={ACCEPTED_EXTENSIONS}
              onChange={handleFileChange}
              hidden
            />
          </section>
        )}
      </main>
    </div>
  );
}

function FilePreviewList({ files, removeFile, formatFileSize, getFileIcon }) {
  return (
    <div className="file-preview-list">
      {files.map((file) => (
        <div className="file-preview" key={file.id}>
          {file.preview ? (
            <img src={file.preview} alt={file.name} />
          ) : (
            <div className="file-preview-icon">{getFileIcon(file)}</div>
          )}

          <div className="file-preview-info">
            <strong>{file.name}</strong>
            <span>{formatFileSize(file.size)}</span>
          </div>

          <button
            type="button"
            onClick={() => removeFile(file.id)}
            aria-label={`Remove ${file.name}`}
          >
            <X size={16} />
          </button>
        </div>
      ))}
    </div>
  );
}

export default MultimodalChat;
